// Run: node src/db/gen_seed.js > src/db/seed100_data.js
// This generates the NEW_PROBLEMS array for seed100.js

const P = (title, statement, tags, difficulty) => ({
  title, statement,
  tags: tags.split(',').map(t => t.trim()),
  difficulty,
  is_curated: true,
})

const problems = [
  // ── ARRAYS (74 more) ────────────────────────────────────────────────────
  P('Two Sum II - Input Array Is Sorted','Given a 1-indexed sorted array, find two numbers that add up to target using O(1) space.','Arrays,Search','Easy'),
  P('Remove Duplicates from Sorted Array','Remove duplicates in-place from a sorted array and return the new length.','Arrays','Easy'),
  P('Remove Element','Remove all occurrences of val in-place and return the new length.','Arrays','Easy'),
  P('Find the Duplicate Number','Find the duplicate number in array of n+1 integers where values are 1 to n.','Arrays','Medium'),
  P('Missing Number','Find the missing number in range [0,n].','Arrays,Hashing','Easy'),
  P('Single Number','Find the element that appears only once; all others appear twice.','Arrays','Easy'),
  P('Majority Element','Find the element that appears more than n/2 times.','Arrays','Easy'),
  P('Pascal Triangle','Generate the first numRows of Pascal triangle.','Arrays','Easy'),
  P('Spiral Matrix','Return all elements of a matrix in spiral order.','Arrays','Medium'),
  P('Set Matrix Zeroes','Set entire row and column to 0 if an element is 0, in-place.','Arrays','Medium'),
  P('Game of Life','Apply Conway Game of Life rules to a board in-place.','Arrays','Medium'),
  P('Maximum Sum Circular Subarray','Find maximum subarray sum in a circular array.','Arrays,DP','Medium'),
  P('Minimum Size Subarray Sum','Find the minimal length subarray with sum >= target.','Arrays,Sliding Window','Medium'),
  P('Longest Consecutive Sequence','Find the length of the longest consecutive sequence in O(n).','Arrays,Hashing','Medium'),
  P('4Sum','Find all unique quadruplets that sum to a target value.','Arrays','Medium'),
  P('Count of Smaller Numbers After Self','Count smaller elements to the right of each element.','Arrays,Sorting','Hard'),
  P('Jump Game III','Starting from index start, determine if you can reach any index with value 0.','Arrays','Medium'),
  P('Minimum Path Sum','Find the minimum path sum from top-left to bottom-right in a grid.','Arrays,DP','Medium'),
  P('Best Time to Buy and Sell Stock II','Maximize profit with unlimited transactions.','Arrays','Medium'),
  P('Best Time to Buy and Sell Stock III','Maximize profit with at most two transactions.','Arrays,DP','Hard'),
  P('Next Permutation','Find the next lexicographically greater permutation in-place.','Arrays','Medium'),
  P('Find All Numbers Disappeared in Array','Find all numbers missing from 1 to n in the array.','Arrays,Hashing','Easy'),
  P('Third Maximum Number','Return the third distinct maximum, or maximum if it does not exist.','Arrays','Easy'),
  P('K Closest Points to Origin','Find k closest points to origin by Euclidean distance.','Arrays,Sorting','Medium'),
  P('Squares of a Sorted Array','Return squares of a sorted array in sorted order.','Arrays','Easy'),
  P('Valid Mountain Array','Check if array forms a valid mountain shape.','Arrays','Easy'),
  P('Minimum Domino Rotations For Equal Row','Find minimum swaps to make all values in a row equal.','Arrays','Medium'),
  P('Monotonic Array','Check if array is monotonically increasing or decreasing.','Arrays','Easy'),
  P('Degree of an Array','Find shortest subarray that has the same degree as the whole array.','Arrays,Hashing','Easy'),
  P('Largest Number','Arrange numbers to form the largest number.','Arrays,Sorting','Medium'),
  P('H-Index','Find H-Index from citations array.','Arrays,Sorting','Medium'),
  P('Minimum Number of Arrows to Burst Balloons','Find minimum arrows to burst all balloons.','Arrays,Sorting','Medium'),
  P('Maximum Gap','Find maximum difference between successive elements in sorted form in O(n).','Arrays,Sorting','Hard'),
  P('Partition Array for Maximum Sum','Partition array to maximize sum with segment length at most k.','Arrays,DP','Medium'),
  P('Max Consecutive Ones III','Find max consecutive 1s with at most k zero flips.','Arrays,Sliding Window','Medium'),
  P('Subarray Product Less Than K','Count subarrays with product strictly less than k.','Arrays,Sliding Window','Medium'),
  P('Minimum Consecutive Cards to Pick Up','Find minimum consecutive cards to include a matching pair.','Arrays,Hashing','Medium'),
  P('Find All Duplicates in an Array','Find all elements that appear exactly twice.','Arrays,Hashing','Medium'),
  P('Car Pooling','Determine if car pooling is feasible given trips and capacity.','Arrays,Sorting','Medium'),
  P('Score After Flipping Matrix','Maximize binary matrix score by row and column flips.','Arrays','Medium'),
  P('Maximum Erasure Value','Find max sum subarray with all unique elements.','Arrays,Sliding Window','Medium'),
  P('Count Number of Nice Subarrays','Count subarrays with exactly k odd numbers.','Arrays,Sliding Window','Medium'),
  P('Minimum Operations to Reduce X to Zero','Find minimum operations removing from ends to reduce X to zero.','Arrays,Sliding Window','Medium'),
  P('Frequency of Most Frequent Element','Find max frequency after at most k increments.','Arrays,Sliding Window','Medium'),
  P('Find Target Indices After Sorting Array','Find indices of target value after sorting the array.','Arrays,Sorting','Easy'),
  P('Rearrange Array Elements by Sign','Rearrange so positives and negatives alternate starting with positive.','Arrays','Medium'),
  P('Remove Duplicates from Sorted Array II','Allow at most two duplicates in sorted array.','Arrays','Medium'),
  P('Gas Station','Find the starting gas station index to complete circular route.','Arrays','Medium'),
  P('Wiggle Subsequence','Find length of longest wiggle subsequence.','Arrays,DP','Medium'),
  P('Permutation in String','Check if any permutation of s1 is a substring of s2.','Arrays,Strings,Sliding Window','Medium'),
  P('Check if Array Is Sorted and Rotated','Check if array is sorted and then rotated.','Arrays','Easy'),
  P('Find Pivot Index','Find leftmost index where left sum equals right sum.','Arrays','Easy'),
  P('Running Sum of 1d Array','Compute running sum of array.','Arrays','Easy'),
  P('Shuffle the Array','Shuffle array in the form [x1,x2..xn,y1,y2..yn] to [x1,y1,x2,y2..].','Arrays','Easy'),
  P('Number of Good Pairs','Count pairs where nums[i] == nums[j] and i < j.','Arrays,Hashing','Easy'),
  P('Count Items Matching a Rule','Count items matching category and name rule.','Arrays','Easy'),
  P('Flipping an Image','Flip binary image horizontally then invert.','Arrays','Easy'),
  P('Matrix Diagonal Sum','Find sum of both diagonals of a square matrix avoiding center overlap.','Arrays','Easy'),
  P('Lucky Numbers in a Matrix','Find lucky numbers (min in row and max in column).','Arrays','Easy'),
  P('Maximum Product of Two Elements','Find max product of two distinct elements after subtracting 1 from each.','Arrays','Easy'),
  P('Diagonal Traverse','Traverse matrix diagonally.','Arrays','Medium'),
  P('Range Sum Query - Immutable','Find sum of array between indices using prefix sums.','Arrays','Easy'),
  P('Range Sum Query 2D - Immutable','Find sum of rectangle region using 2D prefix sums.','Arrays','Medium'),
  P('Maximum Average Subarray I','Find subarray of length k with maximum average.','Arrays,Sliding Window','Easy'),
  P('Minimum Average Difference','Find index with minimum absolute difference of average of first and second halves.','Arrays','Medium'),
  P('Find the Middle Index in Array','Find middle index where left sum equals right sum.','Arrays','Easy'),
  P('Check Whether Two Strings are Almost Equivalent','Check if character frequency differs by at most 3.','Arrays,Strings','Easy'),
  P('Counting Words With a Given Prefix','Count words with a given prefix.','Arrays,Strings','Easy'),
  P('Number of Pairs of Interchangeable Rectangles','Count pairs of rectangles with same width/height ratio.','Arrays,Hashing','Medium'),
  P('Two Out of Three','Find elements present in at least two of three arrays.','Arrays,Hashing','Easy'),
  P('Count Elements With Strictly Smaller and Greater Element','Count elements with both a smaller and larger element in array.','Arrays','Easy'),
  P('Divide a String Into Groups of Size k','Divide string into groups of k with fill character.','Arrays,Strings','Easy'),
  P('Find All K-Distant Indices in an Array','Find all indices within distance k of target value index.','Arrays','Easy'),
  P('Replace All Digits with Characters','Replace digit d with (char before d + d).','Arrays,Strings','Easy'),
  P('Maximum Difference Between Increasing Elements','Find maximum difference nums[j]-nums[i] where i<j.','Arrays','Easy'),

  // ── STRINGS (83 more) ───────────────────────────────────────────────────
  P('Reverse String','Reverse a string in-place.','Strings','Easy'),
  P('Reverse String II','Reverse first k characters for every 2k characters.','Strings','Easy'),
  P('First Unique Character in a String','Find the first non-repeating character index.','Strings,Hashing','Easy'),
  P('Ransom Note','Check if ransom note can be built from magazine characters.','Strings,Hashing','Easy'),
  P('Isomorphic Strings','Check if two strings are isomorphic.','Strings,Hashing','Easy'),
  P('Find the Difference','Find the added letter between two strings.','Strings,Hashing','Easy'),
  P('Detect Capital','Check if word uses capital letters correctly.','Strings','Easy'),
  P('Reverse Vowels of a String','Reverse only the vowels in a string.','Strings','Easy'),
  P('Implement strStr','Return index of first occurrence of needle in haystack.','Strings','Easy'),
  P('Count Binary Substrings','Count substrings with equal consecutive 0s and 1s.','Strings','Easy'),
  P('Number of Segments in a String','Count segments separated by spaces.','Strings','Easy'),
  P('Add Strings','Add two non-negative integers represented as strings.','Strings','Easy'),
  P('Multiply Strings','Multiply two non-negative integers given as strings.','Strings','Medium'),
  P('Integer to Roman','Convert integer to Roman numeral.','Strings','Medium'),
  P('Roman to Integer','Convert Roman numeral to integer.','Strings','Easy'),
  P('Letter Combinations of a Phone Number','Return all possible letter combinations for phone digits.','Strings','Medium'),
  P('Generate Parentheses','Generate all valid combinations of n pairs of parentheses.','Strings','Medium'),
  P('Check if Two String Arrays are Equivalent','Check if joining two string arrays gives the same string.','Strings','Easy'),
  P('Excel Sheet Column Number','Convert Excel column title to number.','Strings','Easy'),
  P('Excel Sheet Column Title','Convert column number to Excel title.','Strings','Medium'),
  P('Bulls and Cows','Count bulls (correct position) and cows (wrong position) in number guess.','Strings,Hashing','Medium'),
  P('Reverse Words in String III','Reverse each word in a string.','Strings','Easy'),
  P('Repeated Substring Pattern','Check if string can be constructed by repeating a substring.','Strings','Easy'),
  P('Student Attendance Record I','Check if student record is eligible for attendance award.','Strings','Easy'),
  P('Longest Word in Dictionary','Find longest word in dictionary that can be built character by character.','Strings','Medium'),
  P('Short Encoding of Words','Find shortest encoding of word list using suffix references.','Strings','Medium'),
  P('Reorganize String','Rearrange string so no two adjacent characters are same.','Strings','Medium'),
  P('Custom Sort String','Reorder string to match order defined by order string.','Strings','Medium'),
  P('Find and Replace Pattern','Find all words matching a given pattern.','Strings,Hashing','Medium'),
  P('Unique Email Addresses','Count unique email addresses after applying rules.','Strings,Hashing','Easy'),
  P('License Key Formatting','Format license key with groups of k chars separated by dashes.','Strings','Easy'),
  P('Toeplitz Matrix','Check if matrix is Toeplitz (diagonals have same value).','Strings,Arrays','Easy'),
  P('Buddy Strings','Check if two strings can be made equal by swapping two characters.','Strings,Hashing','Easy'),
  P('Expressive Words','Count words that can be stretched to match a query.','Strings','Medium'),
  P('Shifting Letters','Shift letters by accumulated suffix sums.','Strings','Medium'),
  P('Broken Calculator','Find minimum operations to reach Y from X using double or decrement.','Strings','Medium'),
  P('Repeated String Match','Find minimum times to repeat A so B is a substring.','Strings','Medium'),
  P('Largest Merge Of Two Strings','Merge two strings to form lexicographically largest result.','Strings','Medium'),
  P('Number of Steps to Reduce a Number to Zero','Count steps to reduce n to 0 with halving or subtract 1.','Strings','Easy'),
  P('Largest Odd Number in String','Find largest odd number substring of a number string.','Strings','Easy'),
  P('Maximum Number of Words Found in Sentences','Find sentence with most words.','Strings','Easy'),
  P('Check if the Sentence Is Pangram','Check if sentence contains every letter of the alphabet.','Strings,Hashing','Easy'),
  P('Percentage of Letter in String','Find percentage of a given letter in string.','Strings','Easy'),
  P('Find Words Containing Character','Find indices of words containing given character.','Strings','Easy'),
  P('Decrypt String from Alphabet to Integer Mapping','Decode string where a-i mapped as 1-9 and j-z as 10# to 26#.','Strings','Easy'),
  P('Largest 3-Same-Digit Number in String','Find largest good integer of length 3 with same digits.','Strings','Easy'),
  P('Number of Strings Containing All Three Characters','Count substrings containing at least one a, b, and c.','Strings,Sliding Window','Medium'),
  P('Minimum Number of Moves to Seat Everyone','Minimize total distance moves for students to seats.','Strings,Sorting','Easy'),
  P('Determine if String Halves Are Alike','Check if two halves of string have equal vowel count.','Strings','Easy'),
  P('Longest Subarray of 1s After Deleting One Element','Find longest subarray of 1s after deleting one element.','Strings,Sliding Window','Medium'),
  P('Count Vowel Substrings of a String','Count substrings containing all 5 vowels and only vowels.','Strings,Hashing','Easy'),
  P('Check if All Characters Have Equal Number of Occurrences','Check if all chars appear same number of times.','Strings,Hashing','Easy'),
  P('Number of Different Integers in a String','Count distinct integers embedded in string.','Strings,Hashing','Easy'),
  P('Capitalize the Title','Capitalize words longer than 2 chars, lowercase others.','Strings','Easy'),
  P('Rearrange Characters to Make Target String','Check if target can be formed from characters in s.','Strings,Hashing','Easy'),
  P('Longest Common Subsequence','Find the length of the longest common subsequence of two strings.','Strings,DP','Medium'),
  P('Longest Increasing Subsequence in String','Find LIS using string characters and their values.','Strings,DP','Medium'),
  P('Regular Expression Matching','Implement regex matching with . and *.','Strings,DP','Hard'),
  P('Wildcard Matching','Implement wildcard matching with ? and *.','Strings,DP','Hard'),
  P('Distinct Subsequences','Count distinct subsequences of string t in s.','Strings,DP','Hard'),
  P('Interleaving String','Check if s3 is formed by interleaving s1 and s2.','Strings,DP','Medium'),
  P('Scramble String','Determine if one string is a scramble of another.','Strings,DP','Hard'),
  P('Palindrome Partitioning','Partition string so every substring is a palindrome.','Strings,DP','Medium'),
  P('Palindrome Partitioning II','Find minimum cuts for palindrome partitioning.','Strings,DP','Hard'),
  P('Word Break II','Return all ways to segment string into dictionary words.','Strings,DP','Hard'),
  P('Minimum Window Subsequence','Find minimum window in s that contains t as subsequence.','Strings,Sliding Window','Hard'),
  P('Count Palindromic Subsequences','Count distinct palindromic subsequences in string.','Strings,DP','Hard'),
  P('Longest Substring with At Least K Repeating Characters','Find longest substring where every character appears at least k times.','Strings,Sliding Window','Medium'),
  P('Find All Anagrams in a String','Find all start indices of anagrams of p in s.','Strings,Sliding Window,Hashing','Medium'),
  P('Substring with Concatenation of All Words','Find all starting indices of substrings that concatenate all words.','Strings,Hashing','Hard'),
  P('Text Justification','Format text with full justification.','Strings','Hard'),
  P('Valid Number','Validate if a string is a valid number.','Strings','Hard'),
  P('Decode String','Decode encoded string with k[encoded_string] pattern.','Strings,Stack/Queue','Medium'),
  P('Number of Atoms','Count atoms in chemical formula.','Strings,Stack/Queue','Hard'),
  P('Simplify Path','Simplify Unix file path.','Strings,Stack/Queue','Medium'),
  P('Remove Duplicate Letters','Remove duplicate letters so result is smallest in lexicographic order.','Strings,Stack/Queue','Medium'),
  P('Remove K Digits','Remove k digits to form smallest possible number.','Strings,Stack/Queue','Medium'),
  P('Longest Valid Parentheses','Find longest valid parentheses substring.','Strings,Stack/Queue','Hard'),
  P('Score of Parentheses','Compute score of balanced parentheses based on rules.','Strings,Stack/Queue','Medium'),
  P('Minimum Add to Make Parentheses Valid','Find minimum additions to make parentheses valid.','Strings,Stack/Queue','Medium'),

  // ── SEARCH / BINARY SEARCH (92 more) ───────────────────────────────────
  P('Guess Number Higher or Lower','Use binary search to guess a number in a range.','Search','Easy'),
  P('Sqrt(x) Newton Method','Compute integer square root using Newton method.','Search','Easy'),
  P('Count Negative Numbers in Sorted Matrix','Count negative numbers in a row-wise and column-wise sorted matrix.','Search,Arrays','Easy'),
  P('First Bad Version','Find the first bad version using binary search.','Search','Easy'),
  P('Search Insert Position','Find index to insert target in sorted array.','Search,Arrays','Easy'),
  P('Peak Index in a Mountain Array','Find the peak index in a mountain array.','Search,Arrays','Medium'),
  P('Find Smallest Letter Greater Than Target','Find the smallest character greater than target in sorted array.','Search','Easy'),
  P('Find K Closest Elements','Find k closest elements to x in sorted array.','Search,Arrays','Medium'),
  P('Find Right Interval','For each interval find the minimum start point right of its end.','Search','Medium'),
  P('Capacity To Ship Packages Within D Days','Find minimum capacity to ship all packages in D days.','Search','Medium'),
  P('Minimum Number of Days to Make m Bouquets','Find minimum days to make m bouquets of k adjacent flowers.','Search','Medium'),
  P('Split Array Largest Sum','Split array into m subarrays minimizing the largest sum.','Search','Hard'),
  P('Find in Mountain Array','Find target in a mountain array using binary search.','Search,Arrays','Hard'),
  P('Count of Range Sum','Count range sums that lie in [lower, upper].','Search','Hard'),
  P('Maximum Value at a Given Index in Bounded Array','Maximize value at index in a bounded array.','Search','Medium'),
  P('Magnetic Force Between Two Balls','Maximize minimum distance between balls placed in baskets.','Search','Medium'),
  P('The K Weakest Rows in a Matrix','Find k weakest rows in a binary matrix.','Search,Arrays','Easy'),
  P('Arranging Coins','Find the number of complete rows of coins.','Search','Easy'),
  P('Find Minimum in Rotated Sorted Array II','Find min in rotated sorted array with duplicates.','Search,Arrays','Hard'),
  P('Search a 2D Matrix II','Search in matrix sorted row-wise and column-wise.','Search,Arrays','Medium'),
  P('Random Pick with Weight','Randomly pick index with probability proportional to weight.','Search','Medium'),
  P('H-Index II','Find H-Index from sorted citations array in O(log n).','Search,Arrays','Medium'),
  P('Heaters','Find minimum heater radius to cover all houses.','Search,Arrays,Sorting','Medium'),
  P('Minimum Absolute Sum Difference','Minimize absolute sum difference by replacing one element.','Search,Arrays','Medium'),
  P('Cutting Ribbons','Find maximum length to cut ribbons into at least k pieces.','Search','Medium'),
  P('Successful Pairs of Spells and Potions','Count pairs of spells and potions with product >= success.','Search,Arrays','Medium'),
  P('Minimize Maximum of Arrays','Minimize the maximum element across two arrays with given operations.','Search','Medium'),
  P('Find the Distance Value Between Two Arrays','Count elements in arr1 with no element in arr2 within distance d.','Search,Arrays','Easy'),
  P('Check if a Number Is Majority Element in Sorted Array','Check if target appears more than n/2 times in sorted array.','Search,Arrays','Easy'),
  P('Find Minimum in BST','Find minimum value node in a BST.','Search,Trees','Easy'),
  P('Kth Missing Positive Number','Find kth missing positive number.','Search,Arrays','Easy'),
  P('Two Sum Less Than K','Find max sum of two elements less than k.','Search,Arrays','Easy'),
  P('Count Pairs Whose Sum is Less than Target','Count pairs with sum less than target.','Search,Arrays','Easy'),
  P('Minimum Time to Complete Trips','Find minimum time for buses to complete given number of trips.','Search','Medium'),
  P('Maximum Running Time of N Computers','Find maximum minutes N computers can run simultaneously.','Search','Hard'),
  P('Minimum Speed to Arrive on Time','Find minimum train speed to arrive on time.','Search','Medium'),
  P('Ugly Number III','Find nth ugly number divisible by a, b, or c.','Search','Medium'),
  P('Nth Magical Number','Find nth magical number divisible by a or b.','Search','Hard'),
  P('Minimum Limit of Balls in a Bag','Minimize maximum balls in any bag after splitting operations.','Search','Medium'),
  P('Maximum Number of Removable Characters','Find maximum k such that s is still subsequence of p after removing characters.','Search,Strings','Medium'),
  P('Special Array With X Elements Greater Than or Equal X','Find x such that exactly x numbers in array >= x.','Search,Arrays','Easy'),
  P('Find the Duplicate','Find duplicate in array using binary search on value range.','Search,Arrays','Medium'),
  P('Smallest Rectangle Enclosing Black Pixels','Find smallest rectangle enclosing all black pixels.','Search,Arrays','Hard'),
  P('Find Peak Element in 2D Matrix','Find a peak element in 2D matrix in O(m log n).','Search,Arrays','Hard'),
  P('Count Complete Tree Nodes','Count nodes in complete binary tree in O(log^2 n).','Search,Trees','Medium'),
  P('Intersection of Two Arrays II','Find intersection of two arrays including duplicates.','Search,Arrays,Hashing','Easy'),
  P('4Sum II','Count tuples from four arrays summing to zero.','Search,Hashing','Medium'),
  P('Missing Ranges','Find missing ranges between lower and upper.','Search,Arrays','Easy'),
  P('Sum of Two Integers','Calculate sum of two integers without + or -.','Search','Medium'),
  P('Divide Two Integers','Divide two integers without multiplication, division or mod.','Search','Medium'),
  P('Pow(x, n)','Implement fast power function.','Search','Medium'),
  P('Super Pow','Compute a^b mod 1337 where b is a large number.','Search','Medium'),
  P('Guess Number Higher or Lower II','Find minimum guaranteed cost to guess number.','Search,DP','Medium'),
  P('Find the Closest Palindrome','Find closest palindrome number.','Search,Strings','Hard'),
  P('Check if Array Is Sorted and Rotated with Binary','Determine rotation point with binary search.','Search,Arrays','Easy'),
  P('Russian Doll Envelopes','Find maximum envelopes that can be Russian doll nested.','Search,DP,Sorting','Hard'),
  P('Longest Increasing Subsequence with Binary Search','Find LIS using patience sorting / binary search.','Search,DP','Medium'),
  P('Count Fair Pairs','Count pairs with sum in [lower, upper].','Search,Arrays','Medium'),
  P('Minimum Cost to Make Array Equal','Find value to make array equal with minimum cost.','Search,Arrays','Hard'),
  P('Minimize the Maximum of Two Arrays','Minimize maximum of two arrays with given operations.','Search','Medium'),
  P('Find Minimum Time to Finish All Jobs','Assign jobs to workers minimizing maximum working time.','Search','Hard'),
  P('Minimum Time to Finish the Race','Minimize race time with tire and pit stop costs.','Search,DP','Hard'),
  P('Maximum Number of Groups Entering a Competition','Maximize groups with strictly more members than previous.','Search,Sorting','Medium'),
  P('Minimum Total Distance Traveled','Minimize total distance robots travel to reach factories.','Search,DP','Hard'),
  P('Median of a Row Wise Sorted Matrix','Find median of row-wise sorted matrix.','Search,Arrays','Hard'),
  P('Smallest Divisor Given a Threshold','Find smallest divisor such that sum of rounded quotients <= threshold.','Search','Medium'),
  P('Find Positive Integer Solution for a Given Equation','Find all pairs (x,y) satisfying f(x,y) == z.','Search','Medium'),
  P('Coordinate With Maximum Network Quality','Find coordinate with maximum network signal quality.','Search,Arrays','Medium'),
  P('Jump Game VI','Maximize score jumping through array using deque.','Search,DP,Stack/Queue','Medium'),
  P('Minimum Number of Operations to Make String Sorted','Count ops to make string sorted by removing suffix characters.','Search,DP','Hard'),
  P('Minimum Cost to Cut a Stick','Find minimum cost to cut a stick at given positions.','Search,DP','Hard'),
  P('Maximum Profit in Job Scheduling','Find maximum profit scheduling non-overlapping jobs.','Search,DP','Hard'),
  P('Minimum Interval to Include Each Query','For each query find minimum length interval containing it.','Search,Sorting','Hard'),
  P('Plates Between Candles','For each query count plates between enclosing candles.','Search,Arrays','Medium'),
  P('Number of Flowers in Full Bloom','Count flowers in bloom for each person arrival time.','Search,Sorting','Hard'),
  P('Find the Longest Valid Obstacle Course','Find longest non-decreasing subsequence ending at each obstacle.','Search,Arrays','Hard'),
  P('Count the Number of Fair Pairs','Count index pairs with sum in given range.','Search,Arrays','Medium'),
  P('Maximum Sum of 3 Non-Overlapping Subarrays','Find maximum sum of three non-overlapping subarrays of size k.','Search,DP','Hard'),
  P('Find the Kth Smallest Sum of a Matrix With Sorted Rows','Find kth smallest sum choosing one element per row.','Search,Arrays','Hard'),
  P('Maximum Tastiness of Candy Basket','Maximize minimum absolute difference between basket prices.','Search,Sorting','Medium'),
  P('Minimum Time to Repair Cars','Find minimum time for mechanics to repair all cars.','Search','Medium'),
  P('Check if There Is a Valid Partition','Check if array can be partitioned into valid subarrays.','Search,DP','Medium'),
  P('Minimize the Maximum Difference of Pairs','Minimize maximum pair difference by choosing p pairs.','Search,Sorting','Medium'),
  P('Minimum Operations to Make Array Continuous','Find minimum ops to make array continuous.','Search,Arrays','Hard'),
  P('Koko Eating Bananas II','Variant: minimize eating speed across multiple piles.','Search','Medium'),
  P('Allocate Books','Allocate minimum number of pages so max pages assigned to a student is minimized.','Search','Hard'),
  P('Aggressive Cows','Place cows in stalls maximizing minimum distance between any two cows.','Search','Hard'),
  P('Book Allocation Problem','Allocate books to students minimizing max pages any student reads.','Search','Hard'),

  // ── TREES (85 more) ─────────────────────────────────────────────────────
  P('Binary Tree Preorder Traversal','Return preorder traversal of a binary tree.','Trees','Easy'),
  P('Binary Tree Inorder Traversal','Return inorder traversal of a binary tree iteratively.','Trees','Easy'),
  P('Binary Tree Postorder Traversal','Return postorder traversal of a binary tree.','Trees','Easy'),
  P('Symmetric Tree','Check if a binary tree is symmetric around its center.','Trees','Easy'),
  P('Binary Tree Zigzag Level Order Traversal','Return zigzag level order traversal of a binary tree.','Trees','Medium'),
  P('Sum of Left Leaves','Find sum of all left leaves in a binary tree.','Trees','Easy'),
  P('Count Univalue Subtrees','Count subtrees where all nodes have the same value.','Trees','Medium'),
  P('Find Largest Value in Each Tree Row','Find the largest value in each row of a binary tree.','Trees','Medium'),
  P('Populating Next Right Pointers in Each Node','Populate next right pointer for each node.','Trees','Medium'),
  P('Flatten Binary Tree to Linked List','Flatten tree to linked list in-place in preorder.','Trees','Medium'),
  P('Path Sum II','Find all root-to-leaf paths with target sum.','Trees','Medium'),
  P('Path Sum III','Count paths that sum to target (start anywhere).','Trees','Medium'),
  P('Sum Root to Leaf Numbers','Sum all numbers formed from root-to-leaf paths.','Trees','Medium'),
  P('Binary Tree Cameras','Minimum cameras to monitor all nodes.','Trees','Hard'),
  P('Distribute Coins in Binary Tree','Find minimum moves to distribute coins evenly in tree.','Trees','Medium'),
  P('House Robber III','Rob houses in a binary tree without robbing directly linked.','Trees,DP','Medium'),
  P('Maximum Binary Tree','Build maximum binary tree from array.','Trees','Medium'),
  P('Second Minimum Node in Binary Tree','Find second minimum value in special binary tree.','Trees','Easy'),
  P('Merge Two Binary Trees','Merge two binary trees by summing overlapping nodes.','Trees','Easy'),
  P('Find Mode in Binary Search Tree','Find mode(s) in a BST.','Trees','Easy'),
  P('Minimum Absolute Difference in BST','Find minimum absolute difference between BST node values.','Trees','Easy'),
  P('Trim a Binary Search Tree','Trim BST so all values are within [low, high].','Trees','Medium'),
  P('Convert Sorted Array to BST','Convert sorted array to height-balanced BST.','Trees','Easy'),
  P('Convert Sorted List to BST','Convert sorted linked list to height-balanced BST.','Trees,Linked List','Medium'),
  P('Delete Node in BST','Delete a node in BST and return the resulting tree.','Trees','Medium'),
  P('Insert into a Binary Search Tree','Insert a value into a BST.','Trees','Medium'),
  P('Search in a Binary Search Tree','Find a node in BST with a given value.','Trees','Easy'),
  P('Range Sum of BST','Find sum of all BST values within range [low, high].','Trees','Easy'),
  P('Recover Binary Search Tree','Two BST nodes are swapped; recover the tree.','Trees','Hard'),
  P('Unique Binary Search Trees','Count structurally unique BSTs with n nodes.','Trees,DP','Medium'),
  P('Unique Binary Search Trees II','Generate all structurally unique BSTs with n nodes.','Trees,DP','Medium'),
  P('Binary Search Tree Iterator','Implement BST iterator with next() and hasNext() in O(h) space.','Trees','Medium'),
  P('Closest Binary Search Tree Value','Find value in BST closest to target.','Trees','Easy'),
  P('Closest Binary Search Tree Value II','Find k values in BST closest to target.','Trees','Hard'),
  P('Inorder Successor in BST','Find in-order successor of a node in BST.','Trees','Medium'),
  P('Inorder Predecessor in BST','Find in-order predecessor of a node in BST.','Trees','Medium'),
  P('Binary Tree Paths','Return all root-to-leaf paths.','Trees','Easy'),
  P('Count Good Nodes in Binary Tree','Count nodes where path from root has no greater value.','Trees','Medium'),
  P('Longest ZigZag Path in Binary Tree','Find longest zigzag path in binary tree.','Trees','Medium'),
  P('Maximum Width of Binary Tree','Find maximum width of binary tree at any level.','Trees','Medium'),
  P('All Nodes Distance K in Binary Tree','Find all nodes at distance k from target node.','Trees','Medium'),
  P('Vertical Order Traversal of Binary Tree','Return vertical order traversal of binary tree.','Trees','Hard'),
  P('Find Duplicate Subtrees','Find all duplicate subtrees in a binary tree.','Trees,Hashing','Medium'),
  P('Print Binary Tree','Print binary tree in a formatted structure.','Trees','Medium'),
  P('Complete Binary Tree Inserter','Insert into complete binary tree maintaining completeness.','Trees','Medium'),
  P('Operations on Tree','Implement lock, unlock, upgrade operations on a tree.','Trees','Medium'),
  P('Sum of Nodes with Even-Valued Grandparent','Find sum of nodes whose grandparent has even value.','Trees','Medium'),
  P('Deepest Leaves Sum','Find sum of values of deepest leaves.','Trees','Medium'),
  P('Maximum Level Sum of Binary Tree','Find level with maximum sum.','Trees','Medium'),
  P('Even Odd Tree','Check if binary tree is Even-Odd tree.','Trees','Medium'),
  P('Check Completeness of Binary Tree','Check if binary tree is complete.','Trees','Medium'),
  P('Cousins in Binary Tree','Check if two nodes are cousins (same depth, different parents).','Trees','Easy'),
  P('Time Needed to Inform All Employees','Find time for information to reach all employees in tree.','Trees,Graphs','Medium'),
  P('N-ary Tree Level Order Traversal','Return level order traversal of an N-ary tree.','Trees','Medium'),
  P('Maximum Depth of N-ary Tree','Find maximum depth of N-ary tree.','Trees','Easy'),
  P('N-ary Tree Preorder Traversal','Return preorder traversal of N-ary tree.','Trees','Easy'),
  P('N-ary Tree Postorder Traversal','Return postorder traversal of N-ary tree.','Trees','Easy'),
  P('Encode N-ary Tree to Binary Tree','Encode and decode N-ary tree as binary tree.','Trees','Hard'),
  P('Lowest Common Ancestor of Binary Tree','Find LCA of two nodes in a binary tree (not BST).','Trees','Medium'),
  P('Lowest Common Ancestor of Deepest Leaves','Find LCA of deepest leaves in binary tree.','Trees','Medium'),
  P('Step-By-Step Directions From Binary Tree Node','Find directions from one node to another.','Trees','Medium'),
  P('Amount of Time for Binary Tree to Be Infected','Find time to infect entire binary tree starting from node.','Trees','Medium'),
  P('Delete Nodes And Return Forest','Delete nodes and return list of remaining tree roots.','Trees','Medium'),
  P('Sum of Distances in Tree','Find sum of distances between all node pairs in tree.','Trees,Graphs','Hard'),
  P('Binary Tree Right Side View Extended','Find nodes visible from right side at every level.','Trees','Medium'),
  P('Leaf-Similar Trees','Check if two trees have the same leaf value sequence.','Trees','Easy'),
  P('Average of Levels in Binary Tree','Find average value of nodes on each level.','Trees','Easy'),
  P('Add One Row to Tree','Add a row of nodes with given value at given depth.','Trees','Medium'),
  P('Find Bottom Left Tree Value','Find the leftmost value in the last row.','Trees','Medium'),
  P('Construct Binary Tree from Postorder and Inorder','Build tree from postorder and inorder traversals.','Trees','Medium'),
  P('Construct Binary Search Tree from Preorder','Construct BST from preorder traversal.','Trees','Medium'),
  P('Verify Preorder Serialization of Binary Tree','Verify if a preorder serialization string is valid.','Trees','Medium'),
  P('Binary Tree Tilt','Find total tilt of binary tree.','Trees','Easy'),
  P('Longest Univalue Path','Find longest path where all nodes have same value.','Trees','Medium'),
  P('Most Frequent Subtree Sum','Find most frequent subtree sum in binary tree.','Trees,Hashing','Medium'),
  P('Find Frequency of Each Subtree Sum','Find all subtree sums and their frequencies.','Trees,Hashing','Medium'),
  P('Pseudo-Palindromic Paths in Binary Tree','Count root-to-leaf paths with at most one odd digit.','Trees','Medium'),
  P('Maximum Product of Splitted Binary Tree','Split tree to maximize product of subtree sums.','Trees','Medium'),
  P('Number of Nodes in Sub-Tree With the Same Label','Count nodes in subtree with same label as root of subtree.','Trees','Medium'),
  P('Count Nodes Equal to Average of Subtree','Count nodes equal to average value of their subtree.','Trees','Medium'),
  P('Check if Two Trees Have Same Structure','Compare two trees for structural equality.','Trees','Easy'),
  P('Symmetric Tree Iterative','Check tree symmetry using iterative BFS approach.','Trees','Easy'),
  P('Mirror Binary Tree','Mirror a binary tree recursively and iteratively.','Trees','Easy'),

  // ── GRAPHS (90 more) ────────────────────────────────────────────────────
  P('Flood Fill','Perform flood fill on an image.','Graphs','Easy'),
  P('Island Perimeter','Calculate perimeter of island in grid.','Graphs','Easy'),
  P('Max Area of Island','Find maximum area of island in binary grid.','Graphs','Medium'),
  P('Number of Provinces','Find number of connected provinces using DFS.','Graphs','Medium'),
  P('Find the Town Judge','Find the town judge who is trusted by everyone.','Graphs','Easy'),
  P('Find Center of Star Graph','Find center node of star graph.','Graphs','Easy'),
  P('All Paths From Source to Target','Find all paths from source to target in DAG.','Graphs','Medium'),
  P('Keys and Rooms','Determine if you can visit all rooms.','Graphs','Medium'),
  P('Evaluate Division','Evaluate division queries from given equations.','Graphs','Medium'),
  P('Possible Bipartition','Check if people can be divided into two groups.','Graphs','Medium'),
  P('Is Graph Bipartite','Check if graph is bipartite.','Graphs','Medium'),
  P('Redundant Connection','Find redundant connection that forms a cycle.','Graphs','Medium'),
  P('Minimum Spanning Tree - Kruskals','Build MST using Kruskal algorithm.','Graphs,Sorting','Medium'),
  P('Minimum Spanning Tree - Prims','Build MST using Prim algorithm.','Graphs','Medium'),
  P('Network Delay Time','Find minimum time for signal to reach all nodes.','Graphs','Medium'),
  P('Find the City With the Smallest Number of Reachable Cities','Find city with fewest neighbors within threshold distance.','Graphs','Medium'),
  P('Cheapest Flights Within K Stops','Find cheapest flight from src to dst with at most k stops.','Graphs','Medium'),
  P('Path With Minimum Effort','Find path from top-left to bottom-right with minimum effort.','Graphs','Medium'),
  P('Swim in Rising Water','Find minimum time to swim from top-left to bottom-right.','Graphs','Hard'),
  P('Alien Dictionary','Find order of characters in alien language from sorted words.','Graphs','Hard'),
  P('Topological Sort','Implement topological sort using DFS and Kahns algorithm.','Graphs','Medium'),
  P('Detect Cycle in Directed Graph','Detect cycle in directed graph using DFS.','Graphs','Medium'),
  P('Detect Cycle in Undirected Graph','Detect cycle in undirected graph using union-find.','Graphs','Medium'),
  P('Shortest Path in Binary Matrix','Find shortest path from top-left to bottom-right in binary matrix.','Graphs','Medium'),
  P('Minimum Cost to Connect All Points','Find minimum cost to connect all points.','Graphs','Medium'),
  P('Critical Connections in a Network','Find all critical connections (bridges) in network.','Graphs','Hard'),
  P('Reconstruct Itinerary','Reconstruct itinerary from airline tickets.','Graphs','Hard'),
  P('Shortest Bridge','Find minimum flips to connect two islands.','Graphs','Medium'),
  P('Making a Large Island','Find maximum island size after changing one 0 to 1.','Graphs','Hard'),
  P('Accounts Merge','Merge accounts with same email addresses.','Graphs,Hashing','Medium'),
  P('Sentence Similarity II','Check if sentences are similar given transitive similarity pairs.','Graphs','Medium'),
  P('Most Stones Removed with Same Row or Column','Find maximum stones that can be removed.','Graphs','Medium'),
  P('Minimize Malware Spread','Remove one node to minimize malware spread.','Graphs','Hard'),
  P('Regions Cut By Slashes','Count regions in grid divided by forward and backward slashes.','Graphs','Medium'),
  P('Satisfiability of Equality Equations','Check if equality and inequality equations are satisfiable.','Graphs','Medium'),
  P('Connecting Cities With Minimum Cost','Find minimum cost to connect all cities.','Graphs','Medium'),
  P('Number of Operations to Make Network Connected','Find minimum cables needed to make network connected.','Graphs','Medium'),
  P('Find Eventual Safe States','Find all nodes that eventually lead to terminal nodes.','Graphs','Medium'),
  P('Parallel Courses','Find minimum number of semesters to finish all courses.','Graphs','Medium'),
  P('Loud and Rich','Find the least loud person who is richer than or equal to each person.','Graphs','Medium'),
  P('Shortest Path Visiting All Nodes','Find shortest path that visits every node in graph.','Graphs','Hard'),
  P('Minimum Height Trees','Find roots of minimum height trees.','Graphs','Medium'),
  P('Bus Routes','Find minimum buses to travel from source to target stop.','Graphs','Hard'),
  P('Open the Lock','Find minimum turns to open lock from 0000.','Graphs','Medium'),
  P('Word Ladder II','Find all shortest transformation sequences.','Graphs','Hard'),
  P('Jump Game IV','Find minimum jumps to reach last index with special jumps.','Graphs','Hard'),
  P('Cut Off Trees for Golf Event','Find minimum steps to cut trees in order of height.','Graphs','Hard'),
  P('Minesweeper','Reveal cells in minesweeper game.','Graphs','Medium'),
  P('Walls and Gates','Fill each empty room with distance to nearest gate.','Graphs','Medium'),
  P('Longest Increasing Path in Matrix','Find longest increasing path in matrix.','Graphs,DP','Hard'),
  P('Remove Invalid Parentheses','Remove minimum invalid parentheses to make string valid.','Graphs,Strings','Hard'),
  P('Race Car','Find minimum instructions to reach target position.','Graphs,DP','Hard'),
  P('Sliding Puzzle','Find minimum moves to solve a 2x3 sliding puzzle.','Graphs','Hard'),
  P('Minimum Genetic Mutation','Find minimum mutations to reach target gene sequence.','Graphs','Medium'),
  P('Snakes and Ladders','Find minimum moves to reach end of snakes and ladders board.','Graphs','Medium'),
  P('Check if There Is a Valid Path in a Grid','Check valid path in grid with directed street tiles.','Graphs','Medium'),
  P('Find if Path Exists in Graph','Check if path exists between source and destination.','Graphs','Easy'),
  P('Number of Ways to Arrive at Destination','Count ways to arrive at destination in minimum time.','Graphs','Medium'),
  P('Graph Valid Tree Extended','Check if edges form valid tree with union-find.','Graphs','Medium'),
  P('Reorder Routes to Make All Paths Lead to the City Zero','Find minimum edge reversals.','Graphs','Medium'),
  P('Count Unreachable Pairs of Nodes','Count pairs of nodes that cannot reach each other.','Graphs','Medium'),
  P('Number of Good Paths','Count paths where max value appears at both ends.','Graphs','Hard'),
  P('Minimum Score of a Path Between Two Cities','Find minimum score path between cities.','Graphs','Medium'),
  P('Detonate the Maximum Bombs','Find maximum bombs detonated from one bomb.','Graphs','Medium'),
  P('Number of Distinct Islands','Count distinct island shapes.','Graphs,Hashing','Medium'),
  P('Pacific Atlantic Water Flow II','Find cells that can reach both Pacific and Atlantic.','Graphs','Medium'),
  P('Surrounded Regions Extended','Capture surrounded regions using DFS boundary marking.','Graphs','Medium'),
  P('Number of Closed Islands','Count islands completely surrounded by water.','Graphs','Medium'),
  P('Number of Enclaves','Count land cells that cannot reach the boundary.','Graphs','Medium'),
  P('Count Sub Islands','Count islands in grid2 that are sub-islands of grid1.','Graphs','Medium'),
  P('Count Servers that Communicate','Count servers that can communicate with at least one other.','Graphs','Medium'),
  P('Number of Islands II','Count islands after each land addition.','Graphs','Hard'),
  P('Largest Component Size by Common Factor','Find largest connected component sharing common factors.','Graphs,Hashing','Hard'),
  P('Similar String Groups','Count groups of similar strings.','Graphs,Strings','Hard'),
  P('Online Election','Find winner at time t using binary search.','Graphs,Search','Medium'),
  P('Web Crawler','Crawl all URLs with same hostname from start URL.','Graphs','Medium'),
  P('Escape the Spreading Fire','Find maximum time before fire to start walking.','Graphs','Hard'),
  P('Minimum Number of Vertices to Reach All Nodes','Find minimum source nodes to reach all nodes in DAG.','Graphs','Medium'),
  P('Find Closest Node to Given Two Nodes','Find node reachable from both with minimum max distance.','Graphs','Medium'),
  P('Longest Cycle in a Graph','Find length of longest cycle in directed graph.','Graphs','Hard'),
  P('Tree Diameter','Find diameter of a general tree (longest path).','Graphs,Trees','Medium'),
  P('Count Nodes With the Highest Score','Count nodes whose removal gives highest product of subtree sizes.','Graphs,Trees','Medium'),
  P('Maximum Total Importance of Roads','Assign values to cities to maximize road importance sum.','Graphs,Sorting','Medium'),
  P('Reachable Nodes In Subdivided Graph','Count reachable nodes in subdivided graph.','Graphs','Hard'),
  P('Minimize Cash Flow','Minimize transactions to settle debts between friends.','Graphs','Hard'),
  P('Strongly Connected Components (Kosaraju)','Find all SCCs in directed graph using Kosarajus algorithm.','Graphs','Hard'),
  P('Articulation Points and Bridges','Find articulation points and bridges in undirected graph.','Graphs','Hard'),

  // ── DYNAMIC PROGRAMMING (81 more) ───────────────────────────────────────
  P('Fibonacci Number','Compute nth Fibonacci number.','DP','Easy'),
  P('N-th Tribonacci Number','Compute nth Tribonacci number.','DP','Easy'),
  P('Min Cost Climbing Stairs','Find min cost to reach top of stairs.','DP','Easy'),
  P('Delete and Earn','Maximize points by deleting elements.','DP,Arrays','Medium'),
  P('Stone Game','Determine if first player can always win stone game.','DP','Medium'),
  P('Stone Game II','Maximize stones collected with variable turn length.','DP','Medium'),
  P('Stone Game III','Determine winner in stone game with choice of 1-3 piles.','DP','Hard'),
  P('Stone Game IV','Determine if first player wins removing any perfect square piles.','DP','Hard'),
  P('Predict the Winner','Predict if player 1 can win the score game.','DP','Medium'),
  P('Paint House','Minimize cost to paint houses with no two adjacent same color.','DP','Medium'),
  P('Paint House II','Minimize cost with k colors and no two adjacent same.','DP','Hard'),
  P('Paint Fence','Count ways to paint fence with n posts and k colors.','DP','Medium'),
  P('Knapsack 0-1','Select items with max value not exceeding weight capacity.','DP','Medium'),
  P('Unbounded Knapsack','Select items with repetition to maximize value within capacity.','DP','Medium'),
  P('Subset Sum Problem','Determine if subset exists with given sum.','DP','Medium'),
  P('Count of Subsets with Given Sum','Count subsets with a given sum.','DP','Medium'),
  P('Rod Cutting Problem','Maximize profit by cutting rod into pieces.','DP','Medium'),
  P('Matrix Chain Multiplication','Find minimum multiplications for chain of matrices.','DP','Hard'),
  P('Egg Drop Problem','Find minimum trials to find critical floor.','DP','Hard'),
  P('Word Break Problem','Determine if string can be segmented into dictionary words.','DP','Medium'),
  P('Burst Balloons','Maximize coins from bursting balloons.','DP','Hard'),
  P('Strange Printer','Find minimum turns to print a string.','DP','Hard'),
  P('Minimum Cost to Cut a Stick Extended','Minimize cost of stick cuts using interval DP.','DP','Hard'),
  P('Zuma Game','Find minimum moves to remove all balls in Zuma.','DP','Hard'),
  P('Optimal Strategy for a Game','Find maximum value collectable from array ends.','DP','Medium'),
  P('Wildcard Matching DP','Match string with wildcard pattern using DP.','DP,Strings','Hard'),
  P('Regular Expression Matching DP','Match string with regex using DP table.','DP,Strings','Hard'),
  P('Count Different Palindromic Subsequences','Count distinct palindromic subsequences.','DP,Strings','Hard'),
  P('Maximum Length of Repeated Subarray','Find max length of subarray appearing in both arrays.','DP,Arrays','Medium'),
  P('Uncrossed Lines','Find maximum uncrossed lines connecting equal values.','DP','Medium'),
  P('Minimum ASCII Delete Sum','Find minimum ASCII sum of deleted characters to equalize strings.','DP,Strings','Medium'),
  P('Edit Distance Extended','Count minimum operations to convert one string to another.','DP,Strings','Hard'),
  P('Shortest Common Supersequence','Find shortest common supersequence of two strings.','DP,Strings','Hard'),
  P('Number of Longest Increasing Subsequence','Count number of longest increasing subsequences.','DP','Medium'),
  P('Maximum Sum of Rectangle No Larger Than K','Find max sum rectangle not larger than k.','DP,Arrays','Hard'),
  P('Range Sum Query - Mutable','Range sum with point updates using Fenwick tree.','DP,Arrays','Medium'),
  P('Count Square Submatrices with All Ones','Count square submatrices filled with ones.','DP,Arrays','Medium'),
  P('Maximal Square','Find the largest square of 1s in binary matrix.','DP,Arrays','Medium'),
  P('Maximal Rectangle','Find largest rectangle in binary matrix.','DP,Arrays,Stack/Queue','Hard'),
  P('Triangle','Find minimum path sum from top to bottom of triangle.','DP','Medium'),
  P('Cherry Pickup','Collect max cherries in two passes through grid.','DP','Hard'),
  P('Cherry Pickup II','Collect max cherries with two robots.','DP','Hard'),
  P('Dungeon Game','Find minimum initial health to rescue princess.','DP','Hard'),
  P('Palindrome Partitioning III','Partition string into k palindromes with minimum changes.','DP,Strings','Hard'),
  P('Strange Printer II','Fill grid with minimum colors.','DP','Hard'),
  P('Count Vowels Permutation','Count strings of length n following vowel rules.','DP','Hard'),
  P('Decode Ways II','Count decode ways with * wildcard.','DP,Strings','Hard'),
  P('Coin Change II','Count combinations to make amount.','DP','Medium'),
  P('Target Sum','Count ways to assign +/- to reach target sum.','DP','Medium'),
  P('Profitable Schemes','Count schemes with at least minProfit using at most n members.','DP','Hard'),
  P('Number of Dice Rolls With Target Sum','Count dice roll combinations that sum to target.','DP','Medium'),
  P('Partition to K Equal Sum Subsets','Check if array can be partitioned into k equal sum subsets.','DP','Medium'),
  P('Maximum Profit in Job Scheduling Extended','Maximize profit from non-overlapping jobs.','DP','Hard'),
  P('Minimum Cost to Merge Stones','Find minimum cost to merge stones into one pile.','DP','Hard'),
  P('Number of Music Playlists','Count playlists of length n with at least k different songs.','DP','Hard'),
  P('Student Attendance Record II','Count attendance records of length n satisfying conditions.','DP','Hard'),
  P('Stickers to Spell Word','Find minimum stickers to spell target word.','DP','Hard'),
  P('Minimum Number of Refueling Stops','Find minimum refueling stops to reach target.','DP','Hard'),
  P('Freedom Trail','Find minimum steps to spell a keyword on rotating ring.','DP','Hard'),
  P('Frog Jump','Determine if frog can cross river jumping on stones.','DP','Hard'),
  P('Maximum Vacation Days','Maximize vacation days across cities.','DP','Hard'),
  P('Best Time to Buy and Sell Stock with Cooldown','Maximize profit with cooldown period.','DP','Medium'),
  P('Best Time to Buy and Sell Stock with Transaction Fee','Maximize profit with transaction fee.','DP','Medium'),
  P('Integer Break','Break integer n to maximize product of parts.','DP','Medium'),
  P('Perfect Squares','Find minimum number of perfect squares summing to n.','DP','Medium'),
  P('Ugly Number II','Find nth ugly number.','DP','Medium'),
  P('Super Ugly Number','Find nth super ugly number with given prime list.','DP','Medium'),
  P('Longest Arithmetic Subsequence','Find length of longest arithmetic subsequence.','DP','Medium'),
  P('Longest Arithmetic Subsequence of Given Difference','Find longest subsequence with given difference.','DP,Hashing','Medium'),
  P('Longest Common Substring','Find length of longest common substring using DP.','DP,Strings','Medium'),
  P('Maximum Product Cutting','Cut rope to maximize product of lengths.','DP','Medium'),
  P('Minimum Cost to Fill Cups','Minimize operations to fill water cups.','DP','Easy'),
  P('Ways to Make a Fair Array','Count ways to remove index making array fair.','DP','Medium'),
  P('Count Ways to Build Rooms','Count ways to build rooms following tree dependency.','DP,Trees','Hard'),
  P('Make the XOR of All Segments Equal to Zero','Maximize zeros in range with XOR constraint.','DP','Hard'),
  P('Number of Ways to Paint N * 3 Grid','Count ways to paint grid with 3 colors.','DP','Hard'),
  P('Count All Possible Routes','Count all routes from start to finish with limited fuel.','DP','Hard'),
  P('Maximize Score After N Operations','Maximize score pairing 2n numbers in n operations.','DP','Hard'),
  P('Minimum XOR Sum of Two Arrays','Minimize XOR sum by permuting second array.','DP','Hard'),

  // ── LINKED LIST (92 more) ───────────────────────────────────────────────
  P('Delete Node in a Linked List','Delete a node given only that node.','Linked List','Medium'),
  P('Middle of the Linked List','Find the middle node of linked list.','Linked List','Easy'),
  P('Palindrome Linked List','Check if linked list is a palindrome.','Linked List','Easy'),
  P('Intersection of Two Linked Lists','Find the intersection node of two linked lists.','Linked List','Easy'),
  P('Linked List Cycle II','Find where cycle begins in linked list.','Linked List','Medium'),
  P('Reverse Linked List II','Reverse linked list from position left to right.','Linked List','Medium'),
  P('Rotate List','Rotate linked list to the right by k places.','Linked List','Medium'),
  P('Swap Nodes in Pairs','Swap every two adjacent nodes.','Linked List','Medium'),
  P('Reverse Nodes in k-Group','Reverse nodes in k-group at a time.','Linked List','Hard'),
  P('Partition List','Partition list so nodes less than x come before nodes >= x.','Linked List','Medium'),
  P('Sort List','Sort linked list in O(n log n) time and O(1) space.','Linked List,Sorting','Medium'),
  P('Odd Even Linked List','Group odd-indexed and even-indexed nodes together.','Linked List','Medium'),
  P('Add Two Numbers','Add two numbers represented as linked lists.','Linked List','Medium'),
  P('Add Two Numbers II','Add two numbers with most significant digit first.','Linked List','Medium'),
  P('Flatten a Multilevel Doubly Linked List','Flatten multilevel doubly linked list.','Linked List','Medium'),
  P('Insert into a Sorted Circular Linked List','Insert value into sorted circular linked list.','Linked List','Medium'),
  P('Design Linked List','Implement singly or doubly linked list.','Linked List','Medium'),
  P('Convert Binary Number in a Linked List to Integer','Convert binary linked list to integer.','Linked List','Easy'),
  P('Remove Zero Sum Consecutive Nodes','Remove consecutive nodes that sum to zero.','Linked List','Medium'),
  P('Next Greater Node In Linked List','Find next greater node for each node.','Linked List,Stack/Queue','Medium'),
  P('Linked List Components','Count connected components of linked list nodes.','Linked List','Medium'),
  P('Split Linked List in Parts','Split linked list into k parts as equally as possible.','Linked List','Medium'),
  P('Reverse Nodes in Even Length Groups','Reverse nodes in even length groups.','Linked List','Medium'),
  P('Delete the Middle Node of a Linked List','Delete middle node of linked list.','Linked List','Medium'),
  P('Remove Nodes From Linked List','Remove nodes with smaller node ahead.','Linked List,Stack/Queue','Medium'),
  P('Maximum Twin Sum of a Linked List','Find maximum twin sum in linked list.','Linked List','Medium'),
  P('Double a Number Represented as a Linked List','Double number represented as linked list.','Linked List','Medium'),
  P('Find the Minimum and Maximum Number of Nodes Between Critical Points','Find min and max distance between critical points.','Linked List','Medium'),
  P('Merge In Between Linked Lists','Merge list2 in between positions a and b of list1.','Linked List','Medium'),
  P('Swapping Nodes in a Linked List','Swap values of kth node from front and back.','Linked List','Medium'),
  P('Design Browser History','Implement browser history with back and forward navigation.','Linked List','Medium'),
  P('Design Front Middle Back Queue','Implement queue with push/pop from front, middle, back.','Linked List,Stack/Queue','Medium'),
  P('All O(1) Data Structure','Implement data structure with O(1) inc, dec, getMaxKey, getMinKey.','Linked List,Hashing','Hard'),
  P('Merge Two Sorted Lists Extended','Compare iterative and recursive merge approaches.','Linked List','Easy'),
  P('Skip List Implementation','Implement a skip list data structure.','Linked List','Hard'),
  P('Doubly Linked List Implementation','Implement doubly linked list with all operations.','Linked List','Medium'),
  P('Flatten Binary Tree to Doubly Linked List','Convert BST to sorted doubly linked list in-place.','Linked List,Trees','Medium'),
  P('Clone a Linked List with Random Pointer Extended','Clone linked list using 3 traversal approach.','Linked List,Hashing','Medium'),
  P('Remove Middle Points in Line Segments','Remove collinear middle points from linked list of segments.','Linked List','Medium'),
  P('Polynomial Addition','Add two polynomials stored as linked lists.','Linked List','Easy'),
  P('Segregate Even and Odd Nodes','Segregate even and odd positioned nodes.','Linked List','Medium'),
  P('Josephus Problem','Find position of survivor in Josephus circle.','Linked List','Medium'),
  P('Implement Stack using Linked List','Implement stack data structure using linked list.','Linked List,Stack/Queue','Easy'),
  P('Implement Queue using Linked List','Implement queue using linked list.','Linked List,Stack/Queue','Easy'),
  P('Circular Linked List Traversal','Traverse and count nodes in a circular linked list.','Linked List','Easy'),
  P('Detect and Remove Loop','Detect loop and remove it from linked list.','Linked List','Medium'),
  P('Merge Sort on Linked List','Apply merge sort algorithm on a linked list.','Linked List,Sorting','Medium'),
  P('Move Last Element to Front','Move last element of linked list to front.','Linked List','Easy'),
  P('Pairwise Swap Elements','Pairwise swap adjacent elements of linked list.','Linked List','Easy'),
  P('Intersection Point of Two Linked Lists','Find meeting point of two linked lists.','Linked List','Easy'),
  P('Find Length of Loop in Linked List','Find length of loop if it exists.','Linked List','Medium'),
  P('Check if Linked List is Circular','Check if linked list is circular.','Linked List','Easy'),
  P('Reverse a Doubly Linked List','Reverse a doubly linked list.','Linked List','Easy'),
  P('Sorted Insert in Doubly Linked List','Insert in sorted doubly linked list.','Linked List','Easy'),
  P('Delete All Occurrences of a Given Key','Delete all nodes with given key.','Linked List','Easy'),
  P('Rotate Doubly Linked List','Rotate doubly linked list by n nodes.','Linked List','Medium'),
  P('Convert a Binary Tree to Doubly Linked List','Flatten BST into a doubly linked list.','Linked List,Trees','Medium'),
  P('Quick Sort on Linked List','Sort linked list using quick sort.','Linked List,Sorting','Hard'),
  P('Flatten a Linked List','Flatten multilevel linked list to single level.','Linked List','Medium'),
  P('Add 1 to Number Represented as Linked List','Increment number represented as linked list.','Linked List','Easy'),
  P('Multiplication of Two Polynomials','Multiply two polynomials stored as linked lists.','Linked List','Medium'),
  P('Merge k Sorted Linked Lists Extended','Merge k sorted lists comparing all approaches.','Linked List,Sorting','Hard'),
  P('First Non-Repeating Character in Stream','Maintain first non-repeating char in stream of characters.','Linked List,Hashing','Medium'),
  P('LFU Cache','Implement Least Frequently Used cache.','Linked List,Hashing','Hard'),
  P('Design Skiplist','Design a skip list that supports search, add, erase.','Linked List','Hard'),
  P('Count Pairs with Given Sum in Doubly Linked List','Count pairs with given sum in sorted DLL.','Linked List','Easy'),
  P('Find Triplet in Doubly Linked List','Find triplet with given sum in sorted DLL.','Linked List','Medium'),
  P('Subtract Last from First in Linked List','Subtract last element from first, second-last from second.','Linked List','Medium'),
  P('Priority Queue using Doubly Linked List','Implement priority queue with DLL.','Linked List','Medium'),
  P('Self Organizing List','Implement move-to-front self organizing list.','Linked List','Medium'),
  P('Memory Efficient Doubly Linked List','Implement XOR doubly linked list using single pointer.','Linked List','Hard'),
  P('Rearrange Linked List','Rearrange so that all even-position nodes come after odd.','Linked List','Medium'),
  P('Reorder List Extended','Compare stack-based and pointer-based reorder approaches.','Linked List','Medium'),
  P('Delete N Nodes After M Nodes','Delete n nodes after every m nodes.','Linked List','Easy'),
  P('Reverse Alternate K Nodes','Reverse alternate k nodes in linked list.','Linked List','Hard'),
  P('Flattening a Linked List','Flatten linked list where each node has a bottom pointer.','Linked List','Medium'),
  P('Arrange Consonants and Vowels','Arrange all consonants before vowels in linked list.','Linked List','Medium'),
  P('Front Balanced Linked List','Maintain front and back balanced linked list.','Linked List','Medium'),
  P('In-Place Reversal in Groups','Reverse linked list in groups of k.','Linked List','Hard'),
  P('Clone K-ary Tree using Linked List','Clone k-ary tree represented with linked list.','Linked List,Trees','Medium'),
  P('Polynomial Evaluation using Linked List','Evaluate polynomial stored as linked list.','Linked List','Easy'),
  P('Swap K-th Node from Beginning and End','Swap kth node from front and back.','Linked List','Medium'),
  P('Linked List to BST','Convert sorted linked list to balanced BST.','Linked List,Trees','Medium'),
  P('Spiral Traversal using Queue and Linked List','Do spiral matrix traversal using queue.','Linked List,Stack/Queue','Medium'),
  P('Implement Deque using Linked List','Implement deque (double-ended queue) with linked list.','Linked List,Stack/Queue','Medium'),
  P('Frequency of each Element in Linked List','Find frequency of each element in linked list.','Linked List,Hashing','Easy'),

  // ── STACK / QUEUE (91 more) ─────────────────────────────────────────────
  P('Valid Parentheses Extended','Match brackets considering all types.','Stack/Queue','Easy'),
  P('Simplify Path Extended','Simplify absolute Unix path using stack.','Stack/Queue,Strings','Medium'),
  P('Basic Calculator','Implement basic calculator for +, -, and parentheses.','Stack/Queue,Strings','Hard'),
  P('Basic Calculator II','Implement calculator for +, -, *, / without parentheses.','Stack/Queue,Strings','Medium'),
  P('Basic Calculator III','Implement calculator with all operators and parentheses.','Stack/Queue,Strings','Hard'),
  P('Decode String Extended','Decode k[string] using stack.','Stack/Queue,Strings','Medium'),
  P('Asteroid Collision','Find state of asteroids after collisions.','Stack/Queue','Medium'),
  P('Remove Duplicate Letters Extended','Remove duplicate letters for smallest result using stack.','Stack/Queue,Strings','Medium'),
  P('132 Pattern','Find 132 pattern in array using stack.','Stack/Queue','Medium'),
  P('Largest Rectangle in Histogram Extended','Compare stack vs divide and conquer.','Stack/Queue,Arrays','Hard'),
  P('Trapping Rain Water Stack','Solve trapping rain water using monotonic stack.','Stack/Queue,Arrays','Hard'),
  P('Maximal Rectangle Stack','Find maximal rectangle using histogram stack approach.','Stack/Queue,Arrays','Hard'),
  P('Number of Visible People Queue','Count visible people from each position in queue.','Stack/Queue,Arrays','Hard'),
  P('Sum of Subarray Minimums','Find sum of minimums of all subarrays.','Stack/Queue,Arrays','Medium'),
  P('Sum of Subarray Ranges','Find sum of ranges of all subarrays.','Stack/Queue,Arrays','Medium'),
  P('Sum of Total Strength','Find total strength of wizards using stack.','Stack/Queue,Arrays','Hard'),
  P('Online Stock Span','Calculate price span for each day in stock market.','Stack/Queue','Medium'),
  P('Next Greater Element I','Find next greater element for each element.','Stack/Queue','Easy'),
  P('Next Greater Element II','Find next greater element in circular array.','Stack/Queue','Medium'),
  P('Next Greater Element III','Find next greater element by rearranging digits.','Stack/Queue','Medium'),
  P('Next Smaller Element','Find next smaller element for each element.','Stack/Queue','Medium'),
  P('Previous Greater Element','Find previous greater element for each element.','Stack/Queue','Medium'),
  P('Previous Smaller Element','Find previous smaller element for each element.','Stack/Queue','Medium'),
  P('Maximum Width Ramp Extended','Find maximum width ramp using monotonic stack.','Stack/Queue,Arrays','Medium'),
  P('Removing Stars From a String','Process string removing stars and preceding characters.','Stack/Queue,Strings','Medium'),
  P('Make the String Great','Remove adjacent pairs of same letter with different case.','Stack/Queue,Strings','Easy'),
  P('Minimum Stack Extended','Compare different implementations of min stack.','Stack/Queue','Medium'),
  P('Design a Stack With Increment Operation','Stack with increment bottom k elements.','Stack/Queue','Medium'),
  P('Maximum Frequency Stack','Pop most frequent element from stack.','Stack/Queue,Hashing','Hard'),
  P('Design Circular Queue','Implement circular queue.','Stack/Queue','Medium'),
  P('Design Circular Deque','Implement circular double ended queue.','Stack/Queue','Medium'),
  P('Moving Average from Data Stream','Compute moving average using sliding window queue.','Stack/Queue','Easy'),
  P('Design Hit Counter','Count hits within last 5 minutes.','Stack/Queue','Medium'),
  P('Task Scheduler','Find minimum intervals to finish tasks with cooldown.','Stack/Queue','Medium'),
  P('Reorganize String Stack','Rearrange string so no two adjacent chars are same.','Stack/Queue,Strings','Medium'),
  P('Minimum Number of Pushes to Type Word','Minimize button pushes to type a word.','Stack/Queue','Medium'),
  P('132 Pattern Extended','Detect 132 pattern comparing stack and O(n^2) approaches.','Stack/Queue,Arrays','Medium'),
  P('Validate Stack Sequences','Check if push and pop sequences are valid.','Stack/Queue','Medium'),
  P('Minimum Cost Tree From Leaf Values','Construct tree with minimum cost from leaf values.','Stack/Queue','Medium'),
  P('Maximum Binary Tree Extended','Build maximum binary tree using stack.','Stack/Queue,Trees','Medium'),
  P('Trapping Rain Water II','Find trapped water in 3D elevation map.','Stack/Queue,Graphs','Hard'),
  P('Sliding Window Minimum','Find minimum in each sliding window using deque.','Stack/Queue,Arrays','Hard'),
  P('Maximum Sliding Window Extended','Compare deque and segment tree approaches.','Stack/Queue,Arrays','Hard'),
  P('Jump Game VI Extended','Maximize score jumping through array with deque DP.','Stack/Queue,DP','Medium'),
  P('Constrained Subsequence Sum','Find max sum of non-empty subsequence within window k.','Stack/Queue,DP','Hard'),
  P('Longest Continuous Subarray With Absolute Diff','Find longest subarray with max-min <= limit.','Stack/Queue,Arrays','Medium'),
  P('Shortest Subarray with Sum at Least K','Find shortest subarray with sum >= k.','Stack/Queue,Arrays','Hard'),
  P('Stock Price Fluctuation','Track max and min stock prices from stream.','Stack/Queue,Hashing','Medium'),
  P('Implement Queue using Arrays','Implement queue using circular array.','Stack/Queue','Easy'),
  P('Implement Stack using Arrays','Implement stack using dynamic array.','Stack/Queue','Easy'),
  P('Balanced Parentheses','Generate all valid balanced parentheses.','Stack/Queue,Strings','Medium'),
  P('Check Balanced Expression','Check balanced expression with different bracket types.','Stack/Queue,Strings','Easy'),
  P('Reverse a Queue','Reverse a queue using stack.','Stack/Queue','Easy'),
  P('Reverse a Stack','Reverse a stack using recursion.','Stack/Queue','Medium'),
  P('Sort a Stack','Sort a stack using recursion.','Stack/Queue','Medium'),
  P('Delete Middle Element of Stack','Delete middle element using recursion.','Stack/Queue','Medium'),
  P('Insert at Bottom of Stack','Insert element at bottom of stack using recursion.','Stack/Queue','Medium'),
  P('Reverse String using Stack','Reverse a string using stack.','Stack/Queue,Strings','Easy'),
  P('Check Palindrome using Stack','Check if string is palindrome using stack.','Stack/Queue,Strings','Easy'),
  P('Infix to Postfix Conversion','Convert infix expression to postfix.','Stack/Queue,Strings','Medium'),
  P('Postfix Evaluation','Evaluate postfix expression.','Stack/Queue,Strings','Easy'),
  P('Prefix to Postfix Conversion','Convert prefix expression to postfix.','Stack/Queue,Strings','Medium'),
  P('Minimum Bracket Reversals','Find minimum bracket reversals to make expression balanced.','Stack/Queue,Strings','Medium'),
  P('The Celebrity Problem','Find the celebrity who is known by all but knows no one.','Stack/Queue','Medium'),
  P('First Non-Repeating Character in Stream Extended','Maintain DLL and map for O(1) first unique.','Stack/Queue,Linked List','Medium'),
  P('K Queues in Array','Implement k queues in a single array efficiently.','Stack/Queue','Hard'),
  P('K Stacks in Array','Implement k stacks in a single array.','Stack/Queue','Hard'),
  P('Interleave First and Second Half of Queue','Interleave first and second halves of queue.','Stack/Queue','Medium'),
  P('LRU Cache Extended','Compare doubly linked list and ordered dict implementations.','Stack/Queue,Linked List','Medium'),
  P('Rotten Oranges Extended','Multi-source BFS for rotting oranges.','Stack/Queue,Graphs','Medium'),
  P('Walls and Gates Extended','Multi-source BFS for walls and gates.','Stack/Queue,Graphs','Medium'),
  P('0-1 BFS','Find shortest path with edge weights 0 or 1 using deque.','Stack/Queue,Graphs','Medium'),
  P('Largest Number After Digit Swaps by Parity','Largest number by swapping digits of same parity.','Stack/Queue','Easy'),
  P('Robot Bounded In Circle','Determine if robot stays bounded in a circle.','Stack/Queue','Medium'),
  P('Number of Recent Calls','Count recent calls in last 3000ms time window.','Stack/Queue','Easy'),
  P('Time Needed to Buy Tickets','Find time for person at position k to buy tickets.','Stack/Queue','Easy'),
  P('Reveal Cards In Increasing Order','Reveal cards in increasing order.','Stack/Queue','Medium'),
  P('Dota2 Senate','Find winner of Dota2 senate voting game.','Stack/Queue','Medium'),
  P('Number of Students Unable to Eat Lunch','Count students unable to get preferred sandwich.','Stack/Queue','Easy'),
  P('Implement Trie Prefix Tree','Implement trie with insert, search, startsWith.','Stack/Queue,Strings','Medium'),
  P('Maximum Nesting Depth of Parentheses','Find maximum nesting depth of parentheses.','Stack/Queue,Strings','Easy'),
  P('Check if Word is Valid After Substitutions','Check if word is valid by substituting abc repeatedly.','Stack/Queue,Strings','Medium'),
  P('Minimum Remove to Make Valid Parentheses','Remove minimum parentheses to make string valid.','Stack/Queue,Strings','Medium'),
  P('Count of Matching Parentheses','Count valid parentheses combinations at each prefix.','Stack/Queue,Strings','Hard'),
  P('Find the Most Competitive Subsequence','Find k length most competitive subsequence.','Stack/Queue,Arrays','Medium'),
  P('Append Characters to String to Make Subsequence','Count chars to append so t is subsequence of s.','Stack/Queue,Strings','Medium'),

  // ── SORTING (91 more) ──────────────────────────────────────────────────
  P('Bubble Sort','Implement bubble sort and analyze its best/worst/average cases.','Sorting','Easy'),
  P('Selection Sort','Implement selection sort with analysis.','Sorting','Easy'),
  P('Insertion Sort','Implement insertion sort and explain when it is optimal.','Sorting','Easy'),
  P('Counting Sort','Implement counting sort for known range integers.','Sorting','Easy'),
  P('Radix Sort','Implement radix sort using counting sort as subroutine.','Sorting','Medium'),
  P('Bucket Sort','Implement bucket sort for uniformly distributed data.','Sorting','Medium'),
  P('Heap Sort','Implement heap sort using max-heap.','Sorting','Medium'),
  P('Tim Sort','Explain Tim Sort combining insertion and merge sort.','Sorting','Medium'),
  P('Shell Sort','Implement shell sort with gap sequence.','Sorting','Medium'),
  P('Pancake Sorting','Sort array using pancake flips only.','Sorting','Medium'),
  P('Sort an Array Stable','Implement stable sort and explain stability.','Sorting','Medium'),
  P('Relative Sort Array','Sort array relative to order defined by another array.','Sorting','Easy'),
  P('Sort Array by Parity','Move even numbers to front.','Sorting','Easy'),
  P('Sort Array by Parity II','Interleave even and odd numbers at correct positions.','Sorting','Easy'),
  P('Sort Array by Increasing Frequency','Sort by frequency, ties broken by decreasing value.','Sorting,Hashing','Easy'),
  P('Custom Comparator Sort','Sort using a custom comparator function.','Sorting','Easy'),
  P('Sort List of Strings by Length','Sort strings by length with tie-breaking alphabetically.','Sorting,Strings','Easy'),
  P('Sort by Second Element','Sort list of pairs by second element.','Sorting','Easy'),
  P('Minimum Number of Swaps to Sort Array','Find minimum swaps to sort an array.','Sorting','Medium'),
  P('Count Inversions in Array','Count inversions using merge sort.','Sorting','Hard'),
  P('Count of Smaller After Self Extended','Count smaller elements using merge sort.','Sorting,Arrays','Hard'),
  P('Reverse Pairs Extended','Count reverse pairs using merge sort.','Sorting,Arrays','Hard'),
  P('Sort Nearly Sorted Array','Sort array where each element is at most k positions away.','Sorting','Medium'),
  P('Chocolate Distribution Problem','Minimize difference between max and min chocolates.','Sorting','Easy'),
  P('Minimum Sum of Absolute Differences','Pair elements minimizing total absolute difference.','Sorting','Medium'),
  P('Minimum Difference Between Sum of Two Subsets','Partition into two subsets minimizing difference.','Sorting,DP','Hard'),
  P('Minimum Cost to Connect Ropes','Find minimum cost to connect all ropes.','Sorting','Medium'),
  P('Find K Pairs with Smallest Sums','Find k pairs with smallest sums from two sorted arrays.','Sorting','Medium'),
  P('Sort Characters By Frequency Extended','Compare bucket sort and priority queue approaches.','Sorting,Hashing','Medium'),
  P('Reorder Data in Log Files','Sort log files with letter logs before digit logs.','Sorting,Strings','Medium'),
  P('Sort Integers by Number of 1 Bits','Sort by count of set bits.','Sorting','Easy'),
  P('Maximum Product of Three Numbers','Find maximum product of three numbers.','Sorting','Easy'),
  P('Sum of Absolute Differences in Sorted Array','Compute absolute difference sums in sorted array.','Sorting,Arrays','Medium'),
  P('Sort Vowels in String','Sort vowels in string keeping consonants in place.','Sorting,Strings','Medium'),
  P('Divide Players into Teams of Equal Skill','Pair players to equalize team skills.','Sorting','Medium'),
  P('Minimum Operations to Make Array Sorted','Find ops to make array sorted by incrementing.','Sorting,DP','Hard'),
  P('Maximum Bags with Full Capacity of Rocks','Maximize fully filled bags given additional rocks.','Sorting','Medium'),
  P('Two City Scheduling','Schedule people between two cities at minimum cost.','Sorting','Medium'),
  P('Assign Cookies','Assign cookies to maximize satisfied children.','Sorting','Easy'),
  P('Minimum Time Difference','Find minimum time difference between list of time points.','Sorting','Medium'),
  P('Minimum Number of Moves to Seat Everyone Extended','Sort and match seats to students.','Sorting','Easy'),
  P('Advantage Shuffle','Maximize advantage against target array.','Sorting','Medium'),
  P('Boats to Save People','Find minimum boats to save people with weight limit.','Sorting','Medium'),
  P('Bag of Tokens Extended','Maximize score with token game using sorted array.','Sorting','Medium'),
  P('Increasing Triplet Subsequence','Check if increasing triplet subsequence exists in O(n).','Sorting','Medium'),
  P('Sort List Extended','Compare top-down and bottom-up merge sort on linked list.','Sorting,Linked List','Medium'),
  P('Meeting Rooms','Determine if a person can attend all meetings.','Sorting','Easy'),
  P('Meeting Rooms II','Find minimum conference rooms for all meetings.','Sorting','Medium'),
  P('Maximum Number of Events That Can Be Attended','Maximize events attended.','Sorting','Medium'),
  P('Maximum Number of Events That Can Be Attended II','Attend at most k events for max value.','Sorting,DP','Hard'),
  P('IPO','Maximize capital by completing at most k projects.','Sorting','Hard'),
  P('Find Median from Data Stream','Find running median using two heaps.','Sorting','Hard'),
  P('Sliding Window Median','Find medians of all sliding windows of size k.','Sorting','Hard'),
  P('Kth Largest Element in Stream','Find kth largest element in a stream.','Sorting','Easy'),
  P('Top K Frequent Words','Find k most frequent words.','Sorting,Hashing','Medium'),
  P('K-th Largest Element in Array Extended','Compare quickselect and heap approaches.','Sorting','Medium'),
  P('K-th Smallest Element in Sorted Matrix','Find kth smallest element in sorted matrix.','Sorting','Medium'),
  P('Find K Closest Elements Extended','Compare binary search and sort-by-distance approaches.','Sorting','Medium'),
  P('Smallest Range Covering Elements from K Lists','Find smallest range including at least one from each list.','Sorting','Hard'),
  P('Merge K Sorted Arrays','Merge k sorted arrays into one sorted array.','Sorting,Arrays','Hard'),
  P('External Sort','Explain external sorting for large datasets.','Sorting','Hard'),
  P('Dutch National Flag Extended','Compare 2-way and 3-way partition approaches.','Sorting,Arrays','Medium'),
  P('Quickselect Algorithm','Find kth smallest using quickselect in average O(n).','Sorting','Medium'),
  P('Median of Medians','Find kth smallest in worst case O(n) time.','Sorting','Hard'),
  P('Sort a Matrix Diagonally','Sort each diagonal of matrix in ascending order.','Sorting,Arrays','Medium'),
  P('Sort the Matrix Diagonals','Sort matrix along all diagonals.','Sorting,Arrays','Medium'),
  P('Minimum Number of Platforms','Find minimum platforms needed for trains at station.','Sorting','Medium'),
  P('Activity Selection Problem','Select maximum non-overlapping activities.','Sorting','Medium'),
  P('Job Sequencing Problem','Maximize profit scheduling jobs with deadlines.','Sorting','Medium'),
  P('Fractional Knapsack','Maximize value in knapsack allowing fractions.','Sorting','Medium'),
  P('Huffman Encoding','Build Huffman tree for optimal prefix coding.','Sorting','Hard'),
  P('Sort by Frequency and Index','Sort by frequency then original index.','Sorting,Hashing','Medium'),
  P('Largest Number Extended','Compare string concatenation approach with custom comparator.','Sorting','Medium'),
  P('Minimum Cost to Hire K Workers','Hire k workers at minimum cost respecting quality ratio.','Sorting','Hard'),
  P('Car Fleet Extended','Compare sorting direction approaches.','Sorting,Stack/Queue','Medium'),
  P('Maximum Overlap Intervals','Find maximum overlapping intervals at any point.','Sorting','Medium'),
  P('Minimum Platforms for Trains Extended','Find min platforms using events sorting.','Sorting','Medium'),
  P('Median Maintenance','Maintain running median efficiently.','Sorting','Hard'),
  P('Count Pairs with Difference K','Count pairs with absolute difference exactly k.','Sorting,Hashing','Easy'),
  P('Sort Array of 0s 1s and 2s Extended','Compare counting and in-place flag approaches.','Sorting,Arrays','Medium'),
  P('Pair Sum in Sorted and Rotated Array','Find pair with given sum in sorted rotated array.','Sorting,Arrays','Medium'),
  P('K Smallest in Unsorted Array','Find k smallest elements using partial sort.','Sorting','Medium'),
  P('Minimum Difference in Two Sorted Arrays','Find k pairs with minimum sum difference.','Sorting','Medium'),
  P('Find Pairs with Given Difference in Sorted Array','Find all pairs with given difference.','Sorting,Arrays','Easy'),
  P('Count Pairs Whose Sum is Greater Than Target','Count pairs with sum > target.','Sorting','Easy'),
  P('Count Triplets with Sum Less Than Given Value','Count triplets with sum less than value.','Sorting','Medium'),
  P('Minimum Absolute Difference Extended','Find all pairs with minimum absolute difference.','Sorting','Easy'),
  P('Maximum Consecutive Gap','Find max gap after sorting all elements.','Sorting','Hard'),

  // ── HASHING (89 more) ─────────────────────────────────────────────────
  P('Two Sum All Pairs','Find all pairs summing to target in array.','Hashing,Arrays','Easy'),
  P('Check Pair with Given Sum','Check if pair exists with given sum.','Hashing','Easy'),
  P('4Sum II Extended','Count tuples using hashmap of pair sums.','Hashing','Medium'),
  P('Group Anagrams Extended','Compare sorted-string and character-count key approaches.','Hashing,Strings','Medium'),
  P('Top K Frequent Elements Extended','Compare heap vs bucket sort with hashing.','Hashing,Sorting','Medium'),
  P('First Recurring Character','Find first character that recurs in string.','Hashing,Strings','Easy'),
  P('Find Itinerary from Tickets','Reconstruct trip itinerary from airline tickets.','Hashing,Graphs','Hard'),
  P('Number of Distinct Substrings','Count distinct substrings using rolling hash.','Hashing,Strings','Medium'),
  P('Longest Subarray Without Repeating','Find length of longest subarray without repeating elements.','Hashing,Arrays','Medium'),
  P('Subarrays with Equal 0s and 1s','Count subarrays with equal number of 0s and 1s.','Hashing,Arrays','Medium'),
  P('Count Subarrays with Given Sum Extended','Count subarrays with sum k using prefix hashmap.','Hashing,Arrays','Medium'),
  P('Contiguous Array','Find max length subarray with equal 0s and 1s.','Hashing,Arrays','Medium'),
  P('Minimum Window Substring Extended','Find minimum window using hashmap and sliding window.','Hashing,Strings,Sliding Window','Hard'),
  P('Longest Palindrome by Rearranging','Find length of longest palindrome using character counts.','Hashing,Strings','Easy'),
  P('Can Form Array','Check if array can be formed from pieces.','Hashing,Arrays','Easy'),
  P('Array of Doubled Pairs','Check if array can be partitioned into doubled pairs.','Hashing,Arrays','Medium'),
  P('Brick Wall','Find minimum bricks crossed by vertical line.','Hashing','Medium'),
  P('Number of Boomerangs','Count boomerang triplets (equal distances).','Hashing','Medium'),
  P('Line Reflection','Check if points are symmetric around vertical line.','Hashing','Medium'),
  P('Jewels and Stones','Count jewel types in stones.','Hashing,Strings','Easy'),
  P('Keyboard Row','Find words typeable on one keyboard row.','Hashing,Strings','Easy'),
  P('Word Pattern Extended','Check word pattern using bidirectional hashmap.','Hashing,Strings','Easy'),
  P('Isomorphic Strings Extended','Check isomorphism using two hash maps.','Hashing,Strings','Easy'),
  P('Find Common Characters','Find common characters across all words.','Hashing,Strings','Easy'),
  P('Maximum Number of Balloons','Count maximum instances of word balloon.','Hashing,Strings','Easy'),
  P('Count Good Triplets','Count triplets satisfying constraints.','Hashing,Arrays','Easy'),
  P('Number of Subarrays with Bounded Maximum','Count subarrays with max in range.','Hashing,Arrays','Medium'),
  P('Check if Array Pairs are Divisible by k','Check if all pairs sum divisible by k.','Hashing,Arrays','Medium'),
  P('Subarray with 0 Sum','Check if subarray with zero sum exists.','Hashing,Arrays','Easy'),
  P('Longest Subarray with Sum K','Find longest subarray with sum equal to k.','Hashing,Arrays','Medium'),
  P('Max Points on Same Slope','Count max points with same slope from one point.','Hashing','Hard'),
  P('Substring with Concatenation of All Words Extended','Find all concatenation substrings using sliding hashmap.','Hashing,Strings','Hard'),
  P('Repeated DNA Sequences','Find all 10-letter DNA sequences appearing more than once.','Hashing,Strings','Medium'),
  P('Encode and Decode TinyURL','Design URL shortener.','Hashing','Medium'),
  P('Design HashSet','Implement hashset without built-in hash table.','Hashing','Easy'),
  P('Design HashMap','Implement hashmap without built-in hash table.','Hashing','Easy'),
  P('Random Pick Index','Pick random index of target value from array.','Hashing','Medium'),
  P('Insert Delete GetRandom O(1)','Design data structure for O(1) insert, delete, random.','Hashing','Medium'),
  P('Insert Delete GetRandom O(1) with Duplicates','Allow duplicates with O(1) operations.','Hashing','Hard'),
  P('Minimum Area Rectangle','Find minimum area rectangle from points.','Hashing','Medium'),
  P('Minimum Area Rectangle II','Find minimum area of any axis-not-aligned rectangle.','Hashing','Medium'),
  P('Most Frequent Subtree Sum Extended','Find most frequent subtree sums with hashmap.','Hashing,Trees','Medium'),
  P('Longest Harmonious Subsequence','Find longest harmonious subsequence.','Hashing,Arrays','Easy'),
  P('First Unique Number','Find first unique number in stream.','Hashing,Linked List','Medium'),
  P('Subarray Sum Divisible by K','Count subarrays with sum divisible by k.','Hashing,Arrays','Medium'),
  P('Continuous Subarray Sum','Check if subarray sum is multiple of k.','Hashing,Arrays','Medium'),
  P('Pairs of Songs With Total Durations Divisible by 60','Count song pairs with sum divisible by 60.','Hashing,Arrays','Medium'),
  P('Check if a String Contains All Binary Codes','Check if string contains all k-bit binary codes.','Hashing,Strings','Medium'),
  P('Longest Consecutive Sequence Extended','Compare sort and union-find approaches.','Hashing,Arrays','Medium'),
  P('Happy Number','Determine if number is happy using cycle detection.','Hashing','Easy'),
  P('Valid Sudoku','Validate sudoku board using hash sets.','Hashing,Arrays','Medium'),
  P('Solve Sudoku','Solve sudoku using backtracking.','Hashing,Arrays','Hard'),
  P('Word Search','Find word in matrix using DFS.','Hashing,Graphs','Medium'),
  P('Word Search II','Find all words in matrix using Trie.','Hashing,Graphs','Hard'),
  P('Fraction to Recurring Decimal','Convert fraction to string detecting recurring part.','Hashing,Strings','Medium'),
  P('Palindrome Permutation','Check if any permutation of string is palindrome.','Hashing,Strings','Easy'),
  P('Find Anagram Mappings','Map each element of A to B where B has same elements.','Hashing,Arrays','Easy'),
  P('Minimum Index Sum of Two Lists','Find common items in two lists with minimum index sum.','Hashing,Arrays','Easy'),
  P('Intersection of Two Arrays','Find distinct intersection of two arrays.','Hashing,Arrays','Easy'),
  P('Find the Difference Extended','Find added letter with XOR and hashmap comparison.','Hashing,Strings','Easy'),
  P('Two Sum III Data Structure Design','Design data structure supporting add and find.','Hashing','Easy'),
  P('Bulls and Cows Extended','Compare single pass and two pass hashmap approaches.','Hashing,Strings','Medium'),
  P('Longest Substring with At Most Two Distinct Characters','Find longest substring with at most 2 distinct chars.','Hashing,Strings,Sliding Window','Medium'),
  P('Longest Substring with At Most K Distinct Characters','Find longest substring with at most k distinct chars.','Hashing,Strings,Sliding Window','Medium'),
  P('Count Number of Distinct Integers After Reverse Operations','Count distinct integers after adding reverses.','Hashing,Arrays','Medium'),
  P('Maximum Sum of Almost Unique Subarray','Find max sum of subarray with at least m distinct elements.','Hashing,Arrays,Sliding Window','Medium'),
  P('Find Words That Can Be Formed by Characters','Count words formable from given characters.','Hashing,Strings','Easy'),
  P('Number of Equivalent Domino Pairs','Count equivalent domino pairs.','Hashing,Arrays','Easy'),
  P('Count Number of Texts','Count possible messages from number key presses.','Hashing,DP','Medium'),
  P('Divide Array Into Equal Pairs','Check if array can be divided into pairs.','Hashing,Arrays','Easy'),
  P('Find Players with Zero or One Losses','Find players with zero and one losses.','Hashing,Arrays','Medium'),
  P('Sum of Unique Elements','Find sum of elements appearing exactly once.','Hashing,Arrays','Easy'),
  P('K-diff Pairs in an Array','Count k-diff unique pairs in array.','Hashing,Arrays','Medium'),
  P('Minimum Operations to Convert Number','Count min operations to convert start to goal.','Hashing','Medium'),
  P('Check Whether Two Strings are Almost Equivalent Extended','Check difference in char freq <= 3.','Hashing,Strings','Easy'),
  P('Count the Number of Consistent Strings','Count strings with only allowed characters.','Hashing,Strings','Easy'),
  P('Count Pairs of Equal Substrings','Count substrings in same positions with equal chars.','Hashing,Strings','Easy'),
  P('Minimum Value to Get Positive Step by Step Sum','Find minimum value to keep prefix sums positive.','Hashing,Arrays','Easy'),
  P('Frequency of the Most Frequent Element Extended','Sliding window + prefix approach for max frequency.','Hashing,Arrays,Sliding Window','Medium'),
  P('Largest Unique Number','Find largest number occurring exactly once.','Hashing,Arrays','Easy'),
  P('Uncommon Words from Two Sentences','Find words appearing exactly once in one sentence.','Hashing,Strings','Easy'),
  P('Unique Number of Occurrences','Check if occurrence counts are all unique.','Hashing,Arrays','Easy'),
  P('Count Number of Bad Pairs','Count pairs where j-i != nums[j]-nums[i].','Hashing,Arrays','Medium'),
  P('Number of Zero-Filled Subarrays','Count subarrays filled with zeros.','Hashing,Arrays','Medium'),
  P('Partition String Into Substrings With Values at Most K','Count minimum substrings with value <= k.','Hashing,Strings','Medium'),
  P('Design Tic-Tac-Toe','Design efficient Tic-Tac-Toe with O(1) move.','Hashing','Medium'),
  P('Design Twitter','Design simplified Twitter with follow and newsfeed.','Hashing','Medium'),
  P('Snapshot Array','Implement array with snapshot functionality.','Hashing,Arrays','Medium'),

]

import { writeFileSync } from 'fs'
const output = `export const NEW_PROBLEMS = [\n${problems.map(p => `  ${JSON.stringify(p)},`).join('\n')}\n]\n`
writeFileSync('src/db/problems_data.js', output)
console.log('Generated', problems.length, 'problems')
